# Generated by Django 5.0.7 on 2025-09-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('index', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.node')),
            ],
            bases=('app.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.module'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rs_type', models.CharField(choices=[('is_subtopic_of', 'Is_Subtopic_Of'), ('is_prerequisite_of', 'Is_Prerequisite_Of'), ('is_corequisite_of', 'Is_Corequisite_Of'), ('is_contrasted_with', 'Is_Contrasted_With'), ('is_applied_in', 'Is_Applied_In')], max_length=255)),
                ('first_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_node_of_rs', to='app.node')),
                ('second_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_node_of_rs', to='app.node')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('learningStyleBreakdown', models.JSONField(blank=True, null=True, verbose_name=[{'Concrete Examples': 32.0, 'Dual Coding': 0.0, 'Elaboration': 48.0, 'Interleaving': 8.0, 'Retrieval Practice': 12.0, 'total_user_messages': 25}])),
                ('enrolled_modules', models.ManyToManyField(blank=True, related_name='students', to='app.module')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.node')),
                ('related_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
            bases=('app.node',),
        ),
    ]
