# Generated by Django 5.2.6 on 2025-09-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('convo_id', models.AutoField(primary_key=True, serialize=False)),
                ('convo_title', models.CharField(max_length=500)),
                ('convo_created_date', models.DateTimeField(auto_now_add=True)),
                ('convo_duration', models.IntegerField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.student')),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-convo_created_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_sender', models.CharField(max_length=20)),
                ('msg_text', models.TextField()),
                ('msg_timestamp', models.DateTimeField(auto_now_add=True)),
                ('msg_context', models.JSONField(blank=True, null=True)),
                ('msg_evaluation', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_user_feedback', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.conversation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.student')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['msg_timestamp'],
                'indexes': [models.Index(fields=['student', 'module'], name='message_student_d8aaa8_idx'), models.Index(fields=['conversation', 'msg_timestamp'], name='message_convers_f36642_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentBloomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloom_summary', models.JSONField(blank=True, default=dict)),
                ('last_processed_msg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloom_records', to='app.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloom_records', to='app.student')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
