# Generated by Django 5.0.7 on 2025-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_load_nodes_and_relationships'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Module',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='enrolled_courses',
            new_name='enrolled_modules',
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
