# Generated by Django 5.2.6 on 2025-09-26 15:23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_custom_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='learningStyle',
            field=models.CharField(blank=True, choices=[('Retrieval Practice', 'retrieval practice'), ('Spaced Practice', 'spaced practice'), ('Elaboration', 'elaboration'), ('Concrete Examples', 'concrete examples'), ('Interleaving', 'interleaving'), ('Dual Coding', 'dual coding')], max_length=255, null=True),
        ),
    ]