# Generated by Django 5.2.6 on 2025-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_load_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learningStyleBreakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
