# Generated by Django 5.2.6 on 2025-09-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuizHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_data', models.JSONField(default=dict)),
                ('student_answers', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories', to='app.student')),
            ],
        ),
    ]
