# Generated by Django 5.0.7 on 2025-09-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250925_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learningStyle',
            field=models.CharField(blank=True, choices=[('retrieval_practice', 'Retrieval Practice'), ('spaced_practice', 'Spaced Practice'), ('elaboration', 'Elaboration'), ('concrete_examples', 'Concrete Examples'), ('interleaving', 'Interleaving'), ('dual_coding', 'Dual Coding')], max_length=255, null=True),
        ),
    ]