# Generated by Django 5.0.7 on 2025-09-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_course_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='title',
        ),
        migrations.AddField(
            model_name='module',
            name='index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
